[Export]
baked_state = false
offer_binder = true
slider_server_url="https://computationalthinking-sliderserver-droplet.plutojl.org"
ignore_cache = [
    "index.jl",
]
create_index = false

[SliderServer]
exclude=[
    # these are in the repo but not used on the website
    # "notebooks/basic_syntax.jl",
    # "notebooks/week12/how_to_collaborate_on_software.jl",

    # don't run homeworks
    "notebooks/week0/hw0.jl",
]
